export default  [  
  {
    title:"1 - Play It Again",
    artist: "Torsten Fenslau",
    cover: "out.jpg",
    file: "Out.mp3",
  }, 
  {
    title:"2 - Burn The Elastic",
    artist: "Kurtis el Khaleel",
    cover: "burn.jpg",
    file: "VioletBurnTheElastic.mp3",
  }, 
  {
    title:"3 - Waves of Life",
    artist: "Acardipane",
    cover: "waves.jpg",
    file: "Waves.mp3",
  }, 
  {
    title:"4 - Everybody",
    artist: "Richard F. & Tio Banks",
    cover: "every.jpg",
    file: "every.mp3",
  },  
  {
    title:"5 - Deep Inside",
    artist: "Roger Lyra",
    cover: "roger.jpg",
    file: "every.mp3",
  },        
  {
    title:"6 - Higher State of Consciousness",
    artist: "Josh Wink",
    cover: "josh.jpg",
    file: "JoshWink-HigherState.mp3",
  },   
  {
    title:"7 - Bombscare",
    artist: "2 Bad Mice",
    cover: "boombscare.jfif",
    file: "Bombscare.mp3",
  },    
  {
    title:"8 - Rollerblade Club",
    artist: "Georg O. Luksch",
    cover: "movin.jfif",
    file: "movin.mp3",
  },   
  {
    title:"9 - The Friction Remix",
    artist: "Trajic",
    cover: "friction.jfif",
    file: "DjTrajic-TheFriction.mp3",
  },      
  {
    title:"10 - Rock the Beet",
    artist: "Trajic",
    cover: "traj.jpg",
    file: "Rock.mp3",
  },    
  {
    title:"11 - Pants R Saggin' ",
    artist: "Trajic",
    cover: "pant.jpg",
    file: "Pant.mp3",
  },    
  {
    title:"12 - Jack The Beat",
    artist: "Jeff Mills",
    cover: "hipo3.jpg",
    file: "wwj.mp3",
  }, 
  {
    title:"13 - Breakdown",
    artist: "Self & Trajic",
    cover: "djselfdjtrajic.jpg",
    file: "Self&TrajicBreakdownMix.mp3",
  },
  {
    title:"14 - To The Three",
    artist: "Eric Vidal & Nick Vidal",
    cover: "phoenix.jpg",
    file: "SP1200-ToTheThree.mp3",
  },
  {
    title:"15 - Waves Of Life",
    artist: "Alberto",
    cover: "alberto.jpg",
    file: "alberto.mp3",
  }, 
  {
    title:"16 - The Freaks",
    artist: "Deeon",
    cover: "freaks.jpg",
    file: "Deeon-TheFreaks.mp3",
  }, 
  {
    title:"17 - Twilight 22",
    artist: "Electric Kingdom",
    cover: "elec.jpg",
    file: "Elec.mp3",
  },      
  {
    title:"18 - We Do It Like This",
    artist: "Icey",
    cover: "ice.jfif",
    file: "djicey-wedoitlikethis.mp3",
  },    
  {
    title:"19 - I Need You",
    artist: "Icey",
    cover: "ineedyou.jpg",
    file: "ineedyou.mp3",
  }, 
  {
    title:"20 - This Is Los Angeles",
    artist: "Mark V. & Poogie Bear",
    cover: "mark.jpg",
    file: "This.mp3",
  },   
  {
    title:"21 - Shake It",
    artist: "Gary Martin",
    cover: "shake.jpg",
    file: "GigiGalaxy-ShakeIt.mp3",
  },      
  {
    title:"22 - Rock The Funky Beats",
    artist: "Natural Born Chillers",
    cover: "natu.jpg",
    file: "Natural.mp3",
  },    
  {
    title:"23 - Destination Unknown",
    artist: "Green Velvet",
    cover: "velv.jpg",
    file: "green.mp3",
  },  
  {
    title:"24 - Hocus Pocus",
    artist: "Irene",
    cover: "hocus.jpg",
    file: "HocusPocus.mp3",
  }, 
  {
    title:"25 - Schöneberg Moonmen Over Marmion",
    artist: "Marmion",
    cover: "hipo2.jpg",
    file: "mar.mp3",
  },  
  {
    title:"26 - Meet Her At The Love Parade",
    artist: "Da Hool",
    cover: "hool.jfif",
    file: "DaHool-MeetLove.mp3",
  },
  {
    title:"27 - Plastic Dreams",
    artist: "Jaydee",
    cover: "jaydee.jfif",
    file: "jay.mp3",
  }, 
  {
    title:"28 - Jack The Beat",
    artist: "Wicked Wipe",
    cover: "hipo4.jpg",
    file: "wwjmix.mp3",
  },     
  {
    title:"29 - Friction",
    artist: "Trajic",
    cover: "friction.jfif",
    file: "DJTrajicFriction.mp3",
  },    
  {
    title:"30 - Show Me Your Face",
    artist: "Trajic",
    cover: "tra.jpg",
    file: "tra.mp3",
  }, 
  {
    title:"31 - I'm Gonna Love You",
    artist: "Summer Junkies",
    cover: "phoenix2.jpg",
    file: "SummerJunkiesIm.mp3",
  },
  {
    title:"32 - Bass Planet Beats",
    artist: "Summer Junkies",
    cover: "planetbass.jpg",
    file: "BassPlanetBeats.mp3",
  },
  {
    title:"33 - Witch Doktor Dark Ages",
    artist: "Armand Van Helden ",
    cover: "doktor.jpg",
    file: "armand.mp3",
  }, 
  {
    title:"34 - Free-Stylin",
    artist: "Flik",
    cover: "mix.jpg",
    file: "mix.mp3",
  }, 
  {
    title:"35 - I Wanna Rock",
    artist: "Nedu",
    cover: "iwana.jpg",
    file: "iwanarock.mp3",
  },
  {
    title:"36 - Atomico '99",
    artist: "Nedu",
    cover: "atomico.jpg",
    file: "atomico.mp3",
  }, 
  {
    title:"37 - Work It",
    artist: "Funk",
    cover: "djfunk.jpg",
    file: "djfunk.mp3",
  },
  {
    title:"38 - That Jack",
    artist: "Insane, To kool Chris",
    cover: "kool.jpg",
    file: "thatjack.mp3",
  }, 
  {
    title:"39 - Some Whores",
    artist: "Insane e To kool Chris",
    cover: "insane.jpg",
    file: "some.mp3",
  }, 
  {
    title:"40 - Brothers & Sisters",
    artist: "To kool Chris",
    cover: "bs.jpg",
    file: "bs.mp3",
  }, 
  {
    title:"41 - The Rebel",
    artist: "To kool Chris",
    cover: "re.jpg",
    file: "rebel.mp3",
  },   
  {
    title:"42 - Godfather Freestyle",
    artist: "Christos Kemanetzidis",
    cover: "godf.jpg",
    file: "black.mp3",
  },  
  {
    title:"43 - Fever Express",
    artist: "George Acosta",
    cover: "fever.jfif",
    file: "GeorgeAcosta-Fever.mp3",
  },  
  {
    title:"44 - Pony",
    artist: "Genwine",
    cover: "pony.jpg",
    file: "gen.mp3",
  },   
  {
    title:"45 - In De Ghetto",
    artist: "The Bad Yard Club",
    cover: "in.jpg",
    file: "in.mp3",
  },     
  {
    title:"46 - The Buddha Monks Funky",
    artist: "Stew Featuring ",
    cover: "move.jpg",
    file: "DJStewBMonks-FF.mp3",
  },      
  {
    title:"47 - Move Your Body",
    artist: "Henrique e Walter",
    cover: "henrique.jpg",
    file: "henrique.mp3",
  },     
  {
    title:"48 - Beachball",
    artist: "Nalin & Kane, Icey's",
    cover: "nalin.jfif",
    file: "nalin.mp3",
  },    
  {
    title:"49 - Good Life Cj's Living Good",
    artist: "Kevin Saunderson",
    cover: "ineed.jpg",
    file: "inner.mp3",
  },   
  {
    title:"50 - Turn Me Out",
    artist: "Kathy Brown",
    cover: "kathy.jpg",
    file: "kathBrownTurnMeOut.mp3",
  },        
  {
    title:"51 - Feel It",
    artist: "Todd Terry",
    cover: "feel.jpg",
    file: "Blurr-FeelIt.mp3",
  },         
  {
    title:"52 - Razen Theme",
    artist: "Todd Terry",
    cover: "raze.jpg",
    file: "raze.mp3",
  },   
  {
    title:"53 - Don't Go",
    artist: "Awesome 3",
    cover: "dont.jpg",
    file: "DontGoAwsome.mp3",
  },  
  {
    title:"54 - Dreams",
    artist: "2 Brothers",
    cover: "dreams.jpg",
    file: "dreams.mp3",
  },    
  {
    title:"55 - Stay in Love",
    artist: "Mon a Q",
    cover: "mon.jpg",
    file: "mon.mp3",
  },        
  {
    title:"56 - Release Me",
    artist: "Angelina",
    cover: "ange.jpg",
    file: "Release.mp3",
  },        
  {
    title:"57 - Set U Free",
    artist: "Planet Soul",
    cover: "setyou.jpg",
    file: "SetUFree.mp3",
  },       
  {
    title:"58 - A Little Bit of Ecstasy",
    artist: "Jocelyn Enriquez",
    cover: "joce.jpg",
    file: "Little.mp3",
  },  
  {
    title:"59 - I Can See",
    artist: "SF Spanish Fly",
    cover: "cansee.jfif",
    file: "sfs.mp3",
  }, 
  {
    title:"60 - Too Nice To Be Real",
    artist: "T 99",
    cover: "t99.jpg",
    file: "t99.mp3",
  }, 
  {
    title:"61 - Mothership - Daft Punk",
    artist: "Scott Grooves",
    cover: "scoot.jpg",
    file: "scoot.mp3",
  },    
  {
    title:"62 - Get Freaky",
    artist: "Flying Steps",
    cover: "freak.jfif",
    file: "MusicInstructorfeat.mp3",
  },   
  {
    title:"63 - Planet Rock",
    artist: "Afrika Bambaataa and WestBam",
    cover: "africa0.jpg",
    file: "africa0.mp3",
  },
  {
    title:"64 - Play at Your Own Risk",
    artist: "Planet Patrol",
    cover: "playat.jpg",
    file: "risk.mp3",
  },  
  {
    title:"65 - The City Of Shamballa",
    artist: "Afrika Bambaataa and WestBam",
    cover: "africa.jpg",
    file: "city.mp3",
  },     
  {
    title:"66 - Al-Naafyish (Time)",
    artist: "Hashim",
    cover: "time.jpg",
    file: "time.mp3",
  },   
  {
    title:"67 - Egypt, Egypt",
    artist: "The Egyptian Lover",
    cover: "egypt.jfif",
    file: "TheEgyptian.mp3",
  },  
  {
    title:"68 - The Party Has Begun",
    artist: "FreeStyle",
    cover: "the.jpg",
    file: "The.mp3",
  }, 
  {
    title:"69 - Don't Stop The Rock",
    artist: "FreeStyle",
    cover: "free.jpg",
    file: "FreeStyleDontStopTheRock.mp3",
  },  
  {
    title:"70 - My Boo",
    artist: "Ghost Town DJs",
    cover: "boo.jpg",
    file: "Boo.mp3",
  },     
  {
    title:"71 - Summertime Summertime",
    artist: "Corina",
    cover: "corina.jpg",
    file: "corina.mp3",
  },     
  {
    title:"72 - Say It's Gonna Rain",
    artist: "Will to Power",
    cover: "will.jpg",
    file: "Say.mp3",
  },      
  {
    title:"73 - Dreamin'",
    artist: "Will to Power",
    cover: "will2.jpg",
    file: "Will2.mp3",
  },    
  {
    title:"74 - No Matter What I Do",
    artist: "Alexia",
    cover: "hipo.jpg",
    file: "alexia.mp3",
  },          
  {
    title:"75 - Push It",
    artist: "Salt-N-Pepa",
    cover: "push.jpg",
    file: "PushIt.mp3",
  },     
  {
    title:"76 - Supersonic",
    artist: "J. J. Fad",
    cover: "sonic.jpg",
    file: "Supersonic.mp3",
  },  
  {
    title:"77 - Let the Music Play",
    artist: "Shannon",
    cover: "letmusic.jpg",
    file: "LettheMusicPlay.mp3",
  },     
  {
    title:"78 - Freak It",
    artist: "Lathun Grady",
    cover: "lathun.jpg",
    file: "LathunGradyFreakIt.mp3",
  },    
  {
    title:"79 - Now And Forever",
    artist: "Nyasia",
    cover: "nyasia.jpg",
    file: "nyasia.mp3",
  },      
  {
    title:"80 - In 2 Night",
    artist: "Nikky Feat B'Side",
    cover: "in2.jpg",
    file: "in2.mp3",
  },   
  {
    title:"81 - So, Tell Me, Tell Me",
    artist: "Shavonne",
    cover: "so.jpg",
    file: "SoTellMeTellMe.mp3",
  },
  {
    title:"82 - They're Playing Our Song",
    artist: "Trinere",
    cover: "trinere.jpg",
    file: "TheyrePlayingOurSong.mp3",
  },
  {
    title:"83 - When I Hear Music",
    artist: "Debbie Deb",
    cover: "wheni.jpg",
    file: "WhenIHearMusic.mp3",
  }, 
  {
    title:"84 - Look Out Weekend",
    artist: "Debbie Deb",
    cover: "lookout.jpg",
    file: "LookoutWeekend.mp3",
  }, 
  {
    title:"85 - Funky Little Beat",
    artist: "Connie",
    cover: "connie.jpg",
    file: "connie.mp3",
  },   
  {
    title:"86 - Take Me In Your Arms",
    artist: "Lil Suzy",
    cover: "lil.jpg",
    file: "LilSuzyTakeMeInYourArms.mp3",
  },   
  {
    title:"87 - In A Dream",
    artist: "Rockell",
    cover: "inadream.jpg",
    file: "InADream.mp3",
  },    
  {
    title:"88 - Fallin Slowly",
    artist: "Shana",
    cover: "shana.jpg",
    file: "shana.mp3",
  },      
  {
    title:"89 - Just Another Lover",
    artist: "Ray Guell",
    cover: "ray.jpg",
    file: "Ray.mp3",
  },       
  {
    title:"90 - Silent Morning",
    artist: "Noel",
    cover: "noel.jpg",
    file: "noel.mp3",
  },         
  {
    title:"91 - In My Eyes",
    artist: "Stevie B",
    cover: "b.jpg",
    file: "b.mp3",
  },       
  {
    title:"92 - I'll Be Loving You",
    artist: "Collage",
    cover: "coll.jpg",
    file: "coll.mp3",
  },     
  {
    title:"93 - Just Like the Wind",
    artist: "Tony Garcia",
    cover: "just.jpg",
    file: "JustLiketheWind.mp3",
  },         
  {
    title:"94 - It Takes Two",
    artist: "Rob Base, EZ Rock",
    cover: "rob.jpg",
    file: "ItTakesTwo.mp3",
  },            
  {
    title:"95 - Jam On It",
    artist: "Newcleus",
    cover: "jam.jpg",
    file: "JamOnIt.mp3",
  },     
  {
    title:"96 - Set It Off ",
    artist: "Strafe",
    cover: "set.jpg",
    file: "SetItOff.mp3",
  },        
  {
    title:"97 - This Is How We Do It",
    artist: "Montell Jordan",
    cover: "this.jpg",
    file: "ThisIsHowWeDoIt.mp3",
  },      
  {
    title:"98 - Mr. Loverman",
    artist: "Shabba Ranks",
    cover: "love.jpg",
    file: "love.mp3",
  },      
  {
    title:"99 - I'll Be Missing You",
    artist: "Puff Daddy",
    cover: "puff.jpg",
    file: "puff.mp3",
  },     
  {
    title:"100 - Killing Me Softly",
    artist: "Fugees",
    cover: "fu.jpg",
    file: "fu.mp3",
  },
];

